### ISSUE TITLE
How to use it with GitHub actions?

### ISSUE THREAD

**Issue by fingerart** [falcondev-oss/github-actions-cache-server#39]
I checked https://gha-cache-server.falcondev.io, which only describes how to deploy, but does not mention any usage with GitHub actions. I have a macOS locally as a self-hosted runner. I wonder if this library can solve the problem of pointing the cache server to the self-built gha-cache-server.

**Comment by LouisHaftmann** [comment]
Since we are patching the runner binary directly, there is no need to use a custom action. Just use the default `actions/cache`.

**Comment by fingerart** [comment]
Thx.
