### ISSUE TITLE
Unable to save cache using buildx

### ISSUE THREAD

**Issue by Ebaneck** [falcondev-oss/github-actions-cache-server#49]
Current setup:

      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: |
            tag1
            tag2
          cache-from: type=gha
          cache-to: type=gha,mode=max
          #file: Dockerfile
          provenance: false
          sbom: false

Cache server logs:

```
[cache-server] ℹ Using database driver: mysql
[cache-server] ℹ Migrating database...
[cache-server] ✔ Database migrated
[cache-server] ℹ Using storage driver: s3
[cache-server] ℹ Cleaning up cache entries older than 90d with schedule 0 0 * * * (next run: 7/2/2024, 12:00:00 AM)
Listening on http://[::]:3000

[cache-server]  ERROR  Response: GET /<secret_token>/_apis/artifactcache/caches > 405
 Method get is not allowed on this route.

  at createError$1 (server/chunks/runtime.mjs:1885:15)
  at matchHandler (server/chunks/runtime.mjs:3025:16)
  at Object.handler (server/chunks/runtime.mjs:3036:19)
  at Object.handler (server/chunks/runtime.mjs:2816:31)
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  at async Server.toNodeHandle (server/chunks/runtime.mjs:3082:7)
```

Actions logs:

```
  time="2024-07-01T12:52:56Z" level=debug msg="load cache http://github-actions-cache:3000/<toto-token>/_apis/artifactcache/cache?keys=buildkit-blob-1-sha256%3A094f5bbe54aeb3d2d501d9249a5cdce3ba496a476093d15a401438306f60ca85&version=693bb7016429d80366022f036f84856888c9f13e00145f5f6f4dce303a38d6f2"
  time="2024-07-01T12:52:56Z" level=debug msg="save cache req http://github-actions-cache:3000/<toto-token>/_apis/artifactcache/caches body={\"key\":\"buildkit-blob-1-sha256:094f5bbe54aeb3d2d501d9249a5cdce3ba496a476093d15a401438306f60ca85\",\"version\":\"693bb7016429d80366022f036f84856888c9f13e00145f5f6f4dce303a38d6f2\"}"
  time="2024-07-01T12:52:56Z" level=error msg="/moby.buildkit.v1.Control/Solve returned error: rpc error: code = Unknown desc = error writing layer blob: Method get is not allowed on this route."
  error writing layer blob: Method get is not allowed on this route.
  ```

**Comment by LouisHaftmann** [comment]
Does it work with the default cache server?

**Comment by Ebaneck** [comment]
> Does it work with the default cache server?

Hello @LouisHaftmann 
Yes, I can confirm it works.

**Comment by LouisHaftmann** [comment]
The docker builder in your workflow for some reason does a GET request instead of POST. Looking at the source code of https://github.com/moby/buildkit, I noticed that it actually does a POST request (https://github.com/moby/buildkit/blob/f7bda278b7e2d1de3d8e3f69c51f967fccf6f55b/vendor/github.com/tonistiigi/go-actions-cache/cache.go#L244). So this either is a bug in our http method matching or the `docker/build-push-action` action is not using the default moby/buildkit.

For now you could try updating `docker/build-push-action`. Maybe that fixes the problem.

**Comment by Ebaneck** [comment]
I tried both v3, v4 and v6 of `docker/build-push-action` and still no luck.

**Comment by LouisHaftmann** [comment]
i'll look into it

**Comment by LouisHaftmann** [comment]
Sorry for the delay!

I just got around to setting up a test instance and everything worked fine.

Could you provide some more details:
- How are you hosting the cache server and actions runner?
- What version of the cache server are you using?
- Are there any more actions debug logs?

**Comment by LouisHaftmann** [comment]
Closing this for now. Feel free to reopen if the issue persists.
