### ISSUE TITLE
Compatibility with GitHub-hosted runners

### ISSUE THREAD

**Issue by cheahjs** [falcondev-oss/github-actions-cache-server#52]
I was wondering what is the story like with GitHub-hosted runners. The current instructions require patching the runner, but this is done on disk prior to launch and is only feasible for self-hosted runners, but with GitHub-hosted runners, any steps that are run inside of a workflow are with an already running runner?

This might require patching the runner in memory - has anyone attempted this before?

**Comment by LouisHaftmann** [comment]
It is probably not possible to use this cache server with Github hosted runners unless Github finally allow overwriting `ACTIONS_CACHE_URL` at runtime

**Comment by LouisHaftmann** [comment]
Closing this for now (more info here https://github.com/actions/toolkit/pull/1695)
