### ISSUE TITLE
Clustering support

### ISSUE THREAD

**Issue by LouisHaftmann** [falcondev-oss/github-actions-cache-server#67]
We are currently storing upload info in memory and upload buffers in the file system. For clustering support we would need to share the upload info and buffers between all instances of the cache server. Sharing upload metadata is no problem but we would need some sort of shared file system for the upload buffers.

**Comment by LouisHaftmann** [comment]
We could also use integrated multipart uploads of the storage drivers but that would make it harder to add new drivers which don't support multipart uploads.

**Comment by LouisHaftmann** [comment]
Using a block storage just for upload buffers would also be possible but makes it way more complicated to deploy.

**Comment by LouisHaftmann** [comment]
What do you think? @DrJume

**Comment by LouisHaftmann** [comment]
(s3 and gcs both support multipart uploads)

**Comment by DrJume** [comment]
> Using a block storage just for upload buffers would also be possible but makes it way more complicated to deploy.

I think for anybody who's deploying a cluster (n>1) of the GHA cache server, it wouldn't be much too much to require using an object storage solution as upload buffer location.

But I'm not sure, if it would be the right tool for job.
