### ISSUE TITLE
Documentation site's SSL cert is invalid 

### ISSUE THREAD

**Issue by SPConrad** [falcondev-oss/github-actions-cache-server#68]
Not exactly a repo "issue" but it's blocking me from being able to try out this tool with a work project. 

https://gha-cache-server.falcondev.io/getting-started
![Screenshot 2024-10-15 at 4 34 35 PM](https://github.com/user-attachments/assets/325c3b94-f49e-49f3-aa4a-b8dd7b8cb7ad)

**Comment by LouisHaftmann** [comment]
That's weird, it works for me. What certificate does it show in your browser?
