### ISSUE TITLE
Usage with auto-updating runner

### ISSUE THREAD

**Issue by kuhnroyal** [falcondev-oss/github-actions-cache-server#73]
Is there some way/ideas on how to modify the runner (https://gha-cache-server.falcondev.io/getting-started#bare-metal) every time it is updated?

**Comment by LouisHaftmann** [comment]
You'd probably need some sort of file watcher to automatically modify the binary on change

**Comment by kuhnroyal** [comment]
Thanks!
Yea probably, will see if I still need this.
Moved most of the runners to new ARC images.
