### ISSUE TITLE
Auto clear DB & storage on breaking changes

### ISSUE THREAD

**Issue by DrJume** [falcondev-oss/github-actions-cache-server#75]
A future major update would require clearing the DB & Storage manually. We would like to make it part of the migration process for seamless upgrades.

**Comment by LouisHaftmann** [comment]
Fixed in https://github.com/falcondev-oss/github-actions-cache-server/releases/tag/v4.0.0

**Comment by LouisHaftmann** [comment]
Fixed in https://github.com/falcondev-oss/github-actions-cache-server/releases/tag/v4.0.0
